services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app_network
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/
      - HOSTNAME=flask-app
    
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app_network

networks:
  app_network: