apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: mmbarki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: "0.1"  
            memory: "300Mi" 
          limits:
            cpu: "0.2"  
            memory: "400Mi"  
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "root"      
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "example"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: mmbarki
spec:
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP
