apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: mmbarki
spec:
  clusterIP: None  # Headless Service
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
