#File added for challenge 15
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-web-to-mongodb
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: mongodb
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: webdb
    - podSelector:
        matchLabels:
          app: webnodb
    ports:
    - protocol: TCP
      port: 27017
