apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: {{ .Values.image.mongodb }}
        ports:
        - containerPort: {{ .Values.ports.mongodb }}
        env:
        - name: MONGO_URL
          value: "mongodb://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/"
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: MONGO_PORT
        resources:
          requests:
            cpu: "0.1"
            memory: "300Mi"
          limits:
            cpu: "0.2"
            memory: "400Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdb
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: webdb
  template:
    metadata:
      labels:
        app: webdb
    spec:
      containers:
      - name: webdb
        image: {{ .Values.image.webdb }}
        ports:
        - containerPort: {{ .Values.ports.webdb }}
        env:
        - name: MONGO_URL
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_HOST
        - name: MONGO_DB_NAME
          value: "{{ .Values.mongodb.dbName }}"
        - name: MONGO_COLLECTION_NAME
          value: "{{ .Values.mongodb.collectionName }}"
        resources:
          requests: {{ .Values.resources.requests | toYaml | nindent 12 }}
          limits: {{ .Values.resources.limits | toYaml | nindent 12 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webnodb
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: webnodb
  template:
    metadata:
      labels:
        app: webnodb
    spec:
      containers:
      - name: webnodb
        image: {{ .Values.image.webnodb }}
        ports:
        - containerPort: {{ .Values.ports.webnodb }}
        resources:
          requests: {{ .Values.resources.requests | toYaml | nindent 12 }}
          limits: {{ .Values.resources.limits | toYaml | nindent 12 }}